(function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({1:[function(require,module,exports){
(function($,Drupal){/**
   * Use this behavior as a template for custom Javascript.
   */Drupal.behaviors.garagaBehavior={attach:function(context,settings){$(document).foundation();$(document).ready(function(){$('[data-interchange]',context).each(function(){var interchange=new Foundation.Interchange($(this));$(window).on('changed.zf.mediaquery',function(){interchange._reflow();});});$('[data-color-popupid]',context).on('click',function(e){e.preventDefault();var $modal=$('#popup-modal');$modal.find('#popup-modal-content').html(buildColorModal($(this)));$modal.trigger('open');});function buildColorModal($colorItem){var title=$colorItem.data('colorTitle');var description=$colorItem.data('colorDescription');var imgUrl=$colorItem.data('colorImgurl');var thumbnailUrl=$colorItem.data('colorThimnailurl');var buildText=$colorItem.data('colorBuildtext');var buildLink=$colorItem.data('colorBuildlink');var $popupDescription='<div class="popup-description"><p>'+description+'</p></div>';var $popupImage='<div class="popup-image">'+'  <img src="'+imgUrl+'">'+'</div>';var $popupActions='';if(buildLink){$popupActions='<div class="popup-actions">'+'  <div class="popup-build">'+'    <a href="'+buildLink+'" class="buttonRond">'+'      <span>'+buildText+'</span>'+'    </a>'+'  </div>'+'</div>';}return'<div class="popup-color">'+$popupDescription+$popupImage+$popupActions+'</div>';}$('[data-product-popupid]',context).on('click',function(e){e.preventDefault();// we need to know if there's already a reveal element ready on the page DOM
// if not we have to create it.
var $modal=$('#popup-modal');var prodId=$(this).data('product-popupid');var url='/'+settings.path.pathPrefix+'popup/'+prodId;$.ajax({url:url,type:'GET',dataType:'html',success:function(response){var $resp=$($(response).find('article#node-'+prodId).html());$modal.find('#popup-modal-content').html($resp);$resp.foundation();// Initialize foundation on the new html content.
$modal.trigger('open');}});});// console.log('executing procedure to change some old font awesome classes not used anymore')
var social=$('.garaga-social .svg-inline--fa');for(var i=0;i<social.length;i++){var $item=$(social[i]);if($item.hasClass('fa-facebook-official')){$item.removeClass('fa-facebook-official');$item.addClass('fa-facebook');}if($item.hasClass('fa-linkedin-square')){$item.removeClass('fa-linkedin-square');$item.addClass('fa-linkedin');}}window.dispatchEvent(new Event('resize'));});}};Drupal.behaviors.megamenuBehavior={attach:function(context,settings){//Set variables on page load
$(document).ready(function(){//|Get the full width of the menu
var width=$('.ultimenu').width();//Get the full width of the users screen
var screen_size=$(window).width();//calculate the offset of the menu
var offset=(screen_size-width)/2;//loop through all .ultimenu__flyout sections
$('section.ultimenu__flyout').each(function(){//check to see if sub menu is normal or MEGA!
if($(this).find('.menu').length==0){//Get the position of the current index
var position=$(this).parent().offset();//Set the margin to a variable!!!
var margin=-position.left;//Set the width and offset of the dropdown
$(this).css('width',screen_size);$(this).css('margin-left',margin);}});});//Set variables on page reload
$(window).resize(function(){clearTimeout(window.resizedFinished);window.resizedFinished=setTimeout(function(){console.log('resizing');//|Get the full width of the menu
var width=$('.ultimenu').width();//Get the full width of the users screen
var screen_size=$(window).width();//calculate the offset of the menu
var offset=(screen_size-width)/2;if($('body').hasClass('hide-band')){var options=$('.block-mainnavigation ul.menu-level-0').children();console.log('Options = '+options.length);options.each(function(){var position=$(this).offset();if($(this).find('> .sub-menu-container').length>0){console.log('Position '+position.left);// this options has a submenu, let's reposition it
var submenu=$(this).find('> .sub-menu-container');$(submenu[0]).attr('style','margin-left:'+-position.left+'px');$('.contact-us-label').parent().attr('style','position: unset;');}});}$('section[class="ultimenu__flyout').each(function(){//check to see if sub menu is normal or MEGA!
if($(this).find('.menu').length==0){//Get the position of the current index
var position=$(this).parent().offset();//Set the margin to a variable!!!
var margin=offset-position.left-131;//Set the width and offset of the dropdown
$(this).css('width',width+width*0.238);$(this).css('margin-left',margin);}});},500);});}};// Mobile menu toggler
Drupal.behaviors.menuMobileBehavior={attach:function(context,settings){$('.c-hamburger',context).click(function(){$(this).toggleClass('is-active');$('html, body').animate({scrollTop:0},'fast');$('.mobile-menu-content').slideToggle('fast');});}};// Toggle Mobile menus submenu menu items
Drupal.behaviors.submenuMobileBehavior={attach:function(context,settings){$('.mobile-submenu-toggler',context).click(function(){var menuItem=$(this).parent();$(this).toggleClass('submenu-opened');$('> .sub-menu-container > .row > .menu',menuItem).slideToggle('fast');$('> .sub-menu-container > .menu-col > .menu',menuItem).slideToggle('fast');});}};// Mobile header clearer
Drupal.behaviors.mobileHeaderBehavior={attach:function(context,settings){ajustWrapperMargin();$(window).resize(function(){ajustWrapperMargin();});}};// Mobile sidebar menu active link
Drupal.behaviors.sidebarMenuMobileBehavior={attach:function(context,settings){// Add active link menu toggler
var activeMenuItem=$('#block-left-sidebar .is-active').text();if(activeMenuItem!==''){$('<div class="mobile-sidebar-active-link">'+activeMenuItem+'</div>',{'class':'mobile-sidebar-active-link'}).prependTo('.block-left-sidebar');}// Toggle sidebar menu
$('.mobile-sidebar-active-link','.block-left-sidebar').click(function(){var nav=$(this).parent();$(this).toggleClass('sidebar-menu-opened');$(nav).children('ul').slideToggle('fast');});}};// Mobile sidebar filters
Drupal.behaviors.sidebarMobileFiltersBehavior={attach:function(context,settings){// Toggle sidebar filters
$('.mobile-sidebar-filter-toggler',context).click(function(){$(this).toggleClass('sidebar-filters-opened');$('.block-blogfiltersandnavigation').slideToggle('fast');});}};// Mobile menu Toggler
Drupal.behaviors.footerBehavior={attach:function(context,settings){$('.footer-columns nav h2',context).click(function(){if($(window).width()<640){var menuItem=$(this).parent();$(this).toggleClass('active');$('.menu',menuItem).slideToggle('fast');}});}};// Mobile language toggler
Drupal.behaviors.languageBehavior={attach:function(context,settings){var isMobile=window.matchMedia("only screen and (max-width : 40em)");var currentLanguage=settings.path.currentLanguage;$('.language-switcher-language-url ul.links li').once().each(function(){if($(this).hasClass(currentLanguage)){$('a',this).addClass('is-active');var activeLanguageLink=$(this).html();$(activeLanguageLink).prependTo('.language-switcher-language-url');}});if(isMobile.matches){var languageToggler=$('.is-active','.language-switcher-language-url');$(languageToggler).once().click(function(){$('.language-switcher-language-url ul.links').slideToggle('fast');return false;});}}};// Mobile language toggler
Drupal.behaviors.extranetBehavior={attach:function(context,settings){var isLoading=false;$('.section-extranet #views-exposed-form-extranet-marketing-search input#edit-submit-extranet,'+'.section-extranet #views-exposed-form-extranet-technic-search input#edit-submit-extranet,'+'.section-extranet #views-exposed-form-extranet-training-search input#edit-submit-extranet,'+'.section-extranet #views-exposed-form-extranet-adp-search input#edit-submit-extranet',context).click(function(){if(!isLoading){$("<p class='loader inline-loader'></p>").insertAfter(this);isLoading=true;}});}};// Helper function to ajust wrapper
// on sticky header
function ajustWrapperMargin(){var headerHeight=$('.main-header').outerHeight();var windowWidth=$(window).width();$('.off-canvas-wrapper').css('margin-top',headerHeight);};// Paragraph accordion
Drupal.behaviors.paragraphAccordionBehavior={attach:function(context,settings){// hide paragraph item with opacity so its still loads
var $accordions=$('.field-paragraph--field-accordion-content, .field-paragraph--field-accordion-child-content',context);$.each($accordions,function(index,accordion){setTimeout(function(){$(accordion).hide();$(accordion).css('opacity','1');$('.field-paragraph--field-accordion-content > div > div >div.paragraph--type--block,'+'.field-paragraph--field-accordion-child-content > div > div >div.paragraph--type--block').css('opacity','1');},2100);});// on click collapse parents
$('.paragraph--type--accordion-parent .field-paragraph--field-accordion-header',context).click(function(){var containerItem=$(this).parent();$(this).toggleClass('active');$('.field-paragraph--field-accordion-content .paragraph:not(".paragraph--type--block")',containerItem).show();$('.field-paragraph--field-accordion-content',containerItem).slideToggle('fast');});// on click collapse children
$('.paragraph--type--accordion-child .field-paragraph--field-accordion-header',context).click(function(){var containerItem=$(this).parent();$('.field-paragraph--field-accordion-child-content .paragraph:not(".paragraph--type--block")',containerItem).show();$('.field-paragraph--field-accordion-child-content',containerItem).slideToggle('fast');});}};})(jQuery,Drupal);

},{}]},{},[1])



//# sourceMappingURL=garaga.js.map
